name: Build for Windows

on:
  push:
    branches:
      - main

  build-windows-executable:
    name: Build Windows Executable
    runs-on: windows-latest
    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.6-release
          tag: 5.6-RELEASE
      - uses: actions/checkout@v4
      - run: git config --global core.protectNTFS false
      - run: swift build -c release --static-swift-stdlib --product chatgpt
      - run: cp .build\release\chatgpt.exe chatgpt.exe
      - uses: actions/upload-artifact@v3
        with:
          name: chatgpt-windows.exe
          path: chatgpt.exe